# Generated by Django 4.0.4 on 2022-05-29 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('published_date', models.DateTimeField(default=datetime.datetime)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
